const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Bullet,
		C3.Behaviors.Platform,
		C3.Plugins.Date,
		C3.Plugins.List,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Button.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random
	];
};
self.C3_JsPropNameTable = [
	{Спрайт: 0},
	{Untitled: 0},
	{Тач: 0},
	{Спрайт2: 0},
	{Текст: 0},
	{Untitled2: 0},
	{goldd: 0},
	{Кнопка: 0},
	{Текст2: 0},
	{Untitled3: 0},
	{Кнопка2: 0},
	{Untitled4: 0},
	{Кнопка3: 0},
	{Untitled5: 0},
	{Untitled6: 0},
	{Кнопка4: 0},
	{обои1: 0},
	{Untitled7: 0},
	{Кнопка5: 0},
	{Кнопка6: 0},
	{Кнопка7: 0},
	{Untitled8: 0},
	{Пуля: 0},
	{Untitled9: 0},
	{Untitled10: 0},
	{Untitled11: 0},
	{Untitled12: 0},
	{Платформер: 0},
	{Untitled13: 0},
	{Текст3: 0},
	{Кнопка8: 0},
	{Кнопка9: 0},
	{Спрайт3: 0},
	{Кнопка10: 0},
	{Дата: 0},
	{Список: 0},
	{Текст4: 0},
	{Tap: 0},
	{vrema: 0}
];

self.InstanceType = {
	Спрайт: class extends self.ISpriteInstance {},
	Untitled: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Untitled2: class extends self.ISpriteInstance {},
	goldd: class extends self.ISpriteInstance {},
	Кнопка: class extends self.IButtonInstance {},
	Текст2: class extends self.ITextInstance {},
	Untitled3: class extends self.ISpriteInstance {},
	Кнопка2: class extends self.IButtonInstance {},
	Untitled4: class extends self.ISpriteInstance {},
	Кнопка3: class extends self.IButtonInstance {},
	Untitled5: class extends self.ISpriteInstance {},
	Untitled6: class extends self.ISpriteInstance {},
	Кнопка4: class extends self.IButtonInstance {},
	обои1: class extends self.IButtonInstance {},
	Untitled7: class extends self.ISpriteInstance {},
	Кнопка5: class extends self.IButtonInstance {},
	Кнопка6: class extends self.IButtonInstance {},
	Кнопка7: class extends self.IButtonInstance {},
	Untitled8: class extends self.ISpriteInstance {},
	Untitled9: class extends self.ISpriteInstance {},
	Untitled10: class extends self.ISpriteInstance {},
	Untitled11: class extends self.ISpriteInstance {},
	Untitled12: class extends self.ISpriteInstance {},
	Untitled13: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	Кнопка8: class extends self.IButtonInstance {},
	Кнопка9: class extends self.IButtonInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Кнопка10: class extends self.IButtonInstance {},
	Дата: class extends self.IInstance {},
	Список: class extends self.IListInstance {},
	Текст4: class extends self.ITextInstance {}
}